version: '3.9'
services:
  gateway:
    image: markuysa/astro-gateway:latest
    container_name: astroGateway
    build: ./apiGateway
    ports:
      - "8086:8086"
    depends_on:
       - astro
       - messages
       - auth
       - postgres
    restart: always
  astro:
    image: markuysa/astro-predictions:latest
    container_name: astrologyService
    build: ./astroService
    working_dir: /app
    ports:
      - "9090:9090"
    depends_on:
      - postgres
    restart: always
  messages:
    image: markuysa/astro-messages:latest
    container_name: messagesSenderService
    build: ./messageSenderService
    working_dir: /app
    ports:
      - "9091:9091"
    depends_on:
      - postgres
    restart: always
  auth:
    image: markuysa/astro-auth:latest
    container_name: authAstroService
    build: ./authService
    working_dir: /app
    ports:
      - "9092:9092"
    depends_on:
      - postgres
    networks:
      default:
        aliases:
            - db
    restart: always
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=islam20011
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
volumes:
  postgres_data: